export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const SET_INTERESTED_OFFICE = 'SET_INTERESTED_OFFICE';
export const SET_USER_VOTES = 'SET_USER_VOTES';
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD';
